<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Authors>OrfeasZ</Authors>
        <Description>Runtime library for Fason.</Description>
        <PackageTags>fsharp;fable;json;fable-library</PackageTags>
        <RepositoryUrl>https://github.com/OrfeasZ/Fason</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Library.fs"/>
        <Content Include="*.fsproj; *.fs" PackagePath="fable/"/>
        <None Include="../README.md" Pack="true" PackagePath="/"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Fable.Core" Version="5.0.0"/>
    </ItemGroup>

</Project>
